const courses = [
    {
        "course-name": "Python for Everyone",
        "course-description": "Kids will explore fun topics while building foundational skills in a playful way.",
        "course-image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT89vO3cvQ4Dc2ADoey15hFhfyUT5XDarEFYg&s",
        "creator": "Abhay K",
        "creator-profile-pic": "https://i.pinimg.com/736x/fa/d5/e7/fad5e79954583ad50ccb3f16ee64f66d.jpg",
        "age-group": [3, 4, 5],
        "grade-group": [1, 2, 3],
        "subject": "Coding & Tech",
        "price-per-class": 25,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 1,
        "class-duration-hr": 1.5,
        "selling-fast": true,
        "creator-rating": 5.0,
        "creator-reviews": 540
    },
    {
        "course-name": "Creative Drawing",
        "course-description": "An engaging and interactive class designed to foster creativity and critical thinking.",
        "course-image": "https://thumbs.dreamstime.com/b/art-workshop-invitation-artistic-course-announcement-creative-painting-classes-exhibition-poster-template-plaster-painter-346921756.jpg",
        "creator": "Sara M",
        "creator-profile-pic": "https://i.pinimg.com/736x/fa/d5/e7/fad5e79954583ad50ccb3f16ee64f66d.jpg",
        "age-group": [6, 7],
        "grade-group": [2, 3],
        "subject": "Arts",
        "price-per-class": 20,
        "currency": "USD",
        "class-type": "One-on-One",
        "class-frequency-per-week": 2,
        "class-duration-hr": 1.0,
        "selling-fast": false,
        "creator-rating": 5.0,
        "creator-reviews": 540,
    },
    {
        "course-name": "Reading Adventures",
        "course-description": "This course helps learners grow confidence through exciting activities and lessons.",
        "course-image": "https://d3jbu7vaxvlagf.cloudfront.net/small/v2/category_media/image_17102218114368.jpeg",
        "creator": "John D",
        "creator-profile-pic": "john-pic.jpg",
        "age-group": [8, 9, 10],
        "grade-group": [3, 4, 5, 6],
        "subject": "English",
        "price-per-class": 30,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 1,
        "class-duration-hr": 2.0,
        "selling-fast": true,
        "creator-rating": 4.5,
        "creator-reviews": 140,
    },
    {
        "course-name": "Math Magic",
        "course-description": "Designed for young learners to explore concepts with games, stories, and crafts.",
        "course-image": "https://static.vecteezy.com/system/resources/thumbnails/028/074/811/small/different-math-graphs-and-objects-math-class-concept-illustration-vector.jpg",
        "creator": "Lina P",
        "creator-profile-pic": "lina-pic.jpg",
        "age-group": [4, 5, 6],
        "grade-group": [2, 3],
        "subject": "Math",
        "price-per-class": 15,
        "currency": "USD",
        "class-type": "One-on-One",
        "class-frequency-per-week": 3,
        "class-duration-hr": 1.0,
        "selling-fast": true,
        "creator-rating": 5.0,
        "creator-reviews": 540,
    },
    {
        "course-name": "Art Explorers",
        "course-description": "A hands-on learning experience with real-world applications for curious minds.",
        "course-image": "https://marketplace.canva.com/EAGQXljjZEA/1/0/1143w/canva-brown-beige-illustration-art-classes-poster-5L7IqHMJCXs.jpg",
        "creator": "Carlos R",
        "creator-profile-pic": "carlos-pic.jpg",
        "age-group": [9, 10, 11, 12],
        "grade-group": [4, 5, 6, 7, 8],
        "subject": "Arts",
        "price-per-class": 35,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 2,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "Junior Game Dev",
        "course-description": "Kids will learn how to design their own video games using fun, easy tools.",
        "course-image": "https://www.cdmi.in/courses@2x/2D3D-Game-Design.webp",
        "creator": "Abhay K",
        "creator-profile-pic": "abhay-pic.jpg",
        "age-group": [7, 8],
        "grade-group": [2, 3, 4],
        "subject": "Coding & Tech",
        "price-per-class": 30,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 2,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "Phonics Fun",
        "course-description": "An interactive and fun class to help young learners master phonics.",
        "course-image": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/editable-phonics-adventure-template-design-acf647f165d67065884888e4c13b885a_screen.jpg?ts=1737532847",
        "creator": "Sara M",
        "creator-profile-pic": "sara-pic.jpg",
        "age-group": [3, 4],
        "grade-group": [1, 2],
        "subject": "English",
        "price-per-class": 20,
        "currency": "USD",
        "class-type": "One-on-One",
        "class-frequency-per-week": 1,
        "class-duration-hr": 1.0
    },
    {
        "course-name": "Scratch Coding",
        "course-description": "A playful approach to learning coding concepts using Scratch.",
        "course-image": "https://d1ng1bucl7w66k.cloudfront.net/ghost-blog/2022/11/Screen-Shot-2022-11-08-at-2.53.59-PM.png",
        "creator": "John D",
        "creator-profile-pic": "john-pic.jpg",
        "age-group": [6, 7, 8],
        "grade-group": [2, 3, 4],
        "subject": "Coding & Tech",
        "price-per-class": 25,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 1,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "Creative Writing",
        "course-description": "Kids will explore their imagination and learn to craft their own stories.",
        "course-image": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/creative-writing-design-template-e7cbd5ba880bc495963a4c5aead018f7_screen.jpg?ts=1667207098",
        "creator": "Lina P",
        "creator-profile-pic": "lina-pic.jpg",
        "age-group": [9, 10, 11],
        "grade-group": [4, 5, 6],
        "subject": "English",
        "price-per-class": 30,
        "currency": "USD",
        "class-type": "One-on-One",
        "class-frequency-per-week": 1,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "Geometry for Kids",
        "course-description": "A fun, interactive class to learn geometry through puzzles and games.",
        "course-image": "https://m.media-amazon.com/images/I/71-NWnCeauL.jpg",
        "creator": "Carlos R",
        "creator-profile-pic": "carlos-pic.jpg",
        "age-group": [8, 9, 10],
        "grade-group": [3, 4, 5],
        "subject": "Math",
        "price-per-class": 25,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 2,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "Tech Tinkers",
        "course-description": "Hands-on learning with robotics and basic engineering for young learners.",
        "course-image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcixfkuANU-WGd_rwPjcknbRBA2wYz0SMAqA&s",
        "creator": "Abhay K",
        "creator-profile-pic": "abhay-pic.jpg",
        "age-group": [6, 7],
        "grade-group": [2, 3],
        "subject": "Coding & Tech",
        "price-per-class": 30,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 1,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "Fun with Fractions",
        "course-description": "A fun and interactive class that introduces the basics of fractions.",
        "course-image": "https://i.ytimg.com/vi/wQgsCubcvhQ/sddefault.jpg",
        "creator": "Sara M",
        "creator-profile-pic": "sara-pic.jpg",
        "age-group": [7, 8, 9],
        "grade-group": [2, 3, 4],
        "subject": "Math",
        "price-per-class": 20,
        "currency": "USD",
        "class-type": "One-on-One",
        "class-frequency-per-week": 2,
        "class-duration-hr": 1.0
    },
    {
        "course-name": "Crafting Joy",
        "course-description": "An arts and crafts course that fosters creativity and imagination.",
        "course-image": "https://thumbs.dreamstime.com/b/art-class-workshop-template-design-kids-art-craft-education-creativity-class-concept-vector-illustration-art-class-workshop-146271036.jpg",
        "creator": "Lina P",
        "creator-profile-pic": "lina-pic.jpg",
        "age-group": [4, 5],
        "grade-group": [1, 2],
        "subject": "Arts",
        "price-per-class": 15,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 2,
        "class-duration-hr": 1.0
    },
    {
        "course-name": "Problem Solving Champs",
        "course-description": "A class to develop critical thinking and problem-solving skills through math puzzles.",
        "course-image": "https://marketplace.canva.com/EAFuRzT_QSA/2/0/1600w/canva-white%2C-red%2C-blue%2C-purple-and-orange%2C-playful%2C-modern%2C-mathematics-class-education-presentation-TIk1MakWXjQ.jpg",
        "creator": "Carlos R",
        "creator-profile-pic": "carlos-pic.jpg",
        "age-group": [10, 11, 12],
        "grade-group": [5, 6, 7],
        "subject": "Math",
        "price-per-class": 30,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 2,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "Story Time Magic",
        "course-description": "A fun and imaginative class where kids will create and tell their own stories.",
        "course-image": "course-image.jpg",
        "creator": "Abhay K",
        "creator-profile-pic": "abhay-pic.jpg",
        "age-group": [4, 5, 6],
        "grade-group": [1, 2],
        "subject": "English",
        "price-per-class": 18,
        "currency": "USD",
        "class-type": "One-on-One",
        "class-frequency-per-week": 2,
        "class-duration-hr": 1.0
    },
    {
        "course-name": "Scratch Game Design",
        "course-description": "Create your own interactive games using Scratch programming.",
        "course-image": "course-image.jpg",
        "creator": "Sara M",
        "creator-profile-pic": "sara-pic.jpg",
        "age-group": [7, 8],
        "grade-group": [2, 3],
        "subject": "Coding & Tech",
        "price-per-class": 28,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 1,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "Math Olympics",
        "course-description": "A competitive math class to develop quick problem-solving skills.",
        "course-image": "course-image.jpg",
        "creator": "Carlos R",
        "creator-profile-pic": "carlos-pic.jpg",
        "age-group": [9, 10, 11],
        "grade-group": [4,5,6],
        "subject": "Math",
        "price-per-class": 32,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 1,
        "class-duration-hr": 2.0
    },
    {
        "course-name": "Science Adventures",
        "course-description": "Exploring the world of science through fun, hands-on experiments.",
        "course-image": "course-image.jpg",
        "creator": "Lina P",
        "creator-profile-pic": "lina-pic.jpg",
        "age-group": [8, 9, 10],
        "grade-group": [3, 4, 5],
        "subject": "Science",
        "price-per-class": 30,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 2,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "Mindful Moments",
        "course-description": "Teaching kids how to practice mindfulness and manage emotions.",
        "course-image": "course-image.jpg",
        "creator": "Abhay K",
        "creator-profile-pic": "abhay-pic.jpg",
        "age-group": [6, 7],
        "grade-group": [1, 2, 3],
        "subject": "Social Skills",
        "price-per-class": 18,
        "currency": "USD",
        "class-type": "One-on-One",
        "class-frequency-per-week": 1,
        "class-duration-hr": 1.0
    },
    {
        "course-name": "Public Speaking for Kids",
        "course-description": "A fun course to build confidence and communication skills.",
        "course-image": "course-image.jpg",
        "creator": "Sara M",
        "creator-profile-pic": "sara-pic.jpg",
        "age-group": [8, 9, 10],
        "grade-group": [3, 4, 5],
        "subject": "English",
        "price-per-class": 25,
        "currency": "USD",
        "class-type": "One-on-One",
        "class-frequency-per-week": 1,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "History Mysteries",
        "course-description": "An exciting way to explore historical events through interactive activities.",
        "course-image": "course-image.jpg",
        "creator": "Carlos R",
        "creator-profile-pic": "carlos-pic.jpg",
        "age-group": [9, 10],
        "grade-group": [4, 5],
        "subject": "Social Studies",
        "price-per-class": 28,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 2,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "Building with LEGO",
        "course-description": "A creative class where kids use LEGO to learn basic engineering concepts.",
        "course-image": "https://static.vecteezy.com/system/resources/thumbnails/028/074/811/small/different-math-graphs-and-objects-math-class-concept-illustration-vector.jpg",
        "creator": "Abhay K",
        "creator-profile-pic": "abhay-pic.jpg",
        "age-group": [4, 5, 6],
        "grade-group": [1, 2],
        "subject": "STEM",
        "price-per-class": 20,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 1,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "Young Architects",
        "course-description": "https://static.vecteezy.com/system/resources/thumbnails/028/074/811/small/different-math-graphs-and-objects-math-class-concept-illustration-vector.jpg",
        "course-image": "course-image.jpg",
        "creator": "Lina P",
        "creator-profile-pic": "lina-pic.jpg",
        "age-group": [9, 10],
        "grade-group": [4, 5],
        "subject": "Math",
        "price-per-class": 32,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 1,
        "class-duration-hr": 1.5
    },
    {
        "course-name": "Music Theory Basics",
        "course-description": "Kids will explore the fundamentals of music through listening and practice.",
        "course-image": "https://static.vecteezy.com/system/resources/thumbnails/028/074/811/small/different-math-graphs-and-objects-math-class-concept-illustration-vector.jpg",
        "creator": "Carlos R",
        "creator-profile-pic": "carlos-pic.jpg",
        "age-group": [6, 7, 8],
        "grade-group": [1, 2, 3],
        "subject": "Music",
        "price-per-class": 25,
        "currency": "USD",
        "class-type": "One-on-One",
        "class-frequency-per-week": 1,
        "class-duration-hr": 1.0
    },
    {
        "course-name": "Writing Comics",
        "course-description": "A fun class where kids create their own comics and graphic novels.",
        "course-image": "course-image.jpg",
        "creator": "Abhay K",
        "creator-profile-pic": "abhay-pic.jpg",
        "age-group": [9, 10],
        "grade-group": [4, 5],
        "subject": "Arts",
        "price-per-class": 30,
        "currency": "USD",
        "class-type": "Group Class",
        "class-frequency-per-week": 1,
        "class-duration-hr": 1.5
    }
];


export default courses